spring:
  application:
    name: interviewiq

  profiles:
    active: local

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

google:
  client-id: ${GOOGLE_CLIENT_ID}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL:onboarding@resend.dev}  