spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/prepnovis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-version: 1
    baseline-description: Initial existing schema      

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
      bootstrap-servers: localhost:9092

      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          max.block.ms: 3000
          request.timeout.ms: 3000
          delivery.timeout.ms: 5000

      consumer:
        group-id: prepnovis-answer-events
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: com.prepnovis.backend.dto.event


gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-3.5-flash
  base-url: https://generativelanguage.googleapis.com/v1beta